version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: dungeonchain
        PROJECT_BIN: dungeond
        PROJECT_DIR: .dungeonchain
        VERSION: v0.1.0
        REPOSITORY: https://github.com/Crypto-Dungeon/dungeonchain.git
        NAMESPACE: DUNGEOND
        GOLANG_VERSION: 1.22-bullseye
        DEBIAN_VERSION: bullseye
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      # - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/neutron/chain.json
      - CHAIN_ID=dungeontest-1
      - GENESIS_URL=https://github.com/cosmos/testnets/blob/master/interchain-security/dungeontest-1/genesis.json.gz
      #- P2P_SEEDS=e2c07e8e6e808fb36cca0fc580e31216772841df@p2p-palvus.pion-1.ntrn.tech:26656
      - P2P_PERSISTENT_PEERS=9c9affab7652c9c5a2898d0dd244840c90bc8ba9@dungeon-cherry.ics-testnet.polypore.xyz:26656,4c9fe209358b0821fe48be7e449a3ed02af7b740@dungeon.ics-testnet.polypore.xyz:26656
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.dungeonchain
