version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: stride
        PROJECT_BIN: strided
        VERSION: 3aeb075f36cb12711201a7f17e8b8d856bd99a01
        REPOSITORY: https://github.com/Stride-Labs/stride
        NAMESPACE: STRIDED
        PROJECT_DIR: .stride
        GOLANG_VERSION: 1.19-buster
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/chain.json
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.stride
