version: '3.4'

services:
  node:
    build:
      context: ../
      args:
        PROJECT: nomic
        VERSION: v12.0.2
        REPOSITORY: https://github.com/nomic-io/nomic
        NAMESPACE: TM
        DEBIAN_VERSION: bullseye
        BUILD_IMAGE: rustlang/rust:nightly-bullseye
        BUILD_PACKAGES: build-essential pkg-config clang
        BUILD_CMD: cargo install --path . --locked --bin nomic
        BASE_PACKAGES: libssl-dev
        BINARY_PATH: /usr/local/cargo/bin/nomic
        PROJECT_DIR: .nomic-stakenet-3/tendermint
        VERSION_CMD: nomic --version
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      # - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/nomic/chain.json
      - CHAIN_ID=nomic-stakenet-3
      - DOWNLOAD_GENESIS=0
      - INIT_CONFIG=0
    volumes:
      - ./node-data:/root/.nomic-stakenet-3
      # - ./orga-wallet:/root/.orga-wallet
