version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: nomic
        VERSION: v7.0.1
        REPOSITORY: https://github.com/nomic-io/nomic
        NAMESPACE: TM
        BASE_IMAGE: rustlang/rust:nightly-buster
        INSTALL_PACKAGES: build-essential libssl-dev pkg-config clang
        BUILD_CMD: cargo install --path . --locked --bin nomic
        BUILD_PATH: /usr/local/cargo/bin
        PROJECT_DIR: .nomic-stakenet-3/tendermint
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      # - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/nomic/chain.json
      - CHAIN_ID=nomic-stakenet-3
      - DOWNLOAD_GENESIS=0
      - INIT_CONFIG=0
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.nomic-stakenet-3
      # - ./orga-wallet:/root/.orga-wallet
